language: rust
rust:
  - nightly
addons:
  apt:
    packages:
      - binutils-dev
      - jackd
      - libcurl4-openssl-dev
      - libdw-dev
      - libelf-dev
      - libjack-dev
      - libjack0
